"use client";

import { notFound } from "next/navigation";
import { BarChart, Card, DateRangePicker, Grid, Select, SelectItem, Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow, Text, Title } from "@tremor/react";
import { BookOpen01Icon, Calendar02Icon, CalendarCheckIcon, ChartLineData01Icon, Clock01Icon, Download03Icon, FilterHorizontalIcon, Invoice03Icon, Megaphone01Icon, MoneyReceiveCircleIcon, School01Icon, SecurityCheckIcon, Settings02Icon, StudentCardIcon, StudentsIcon, Target02Icon, TaskDone01Icon, TeacherIcon, UserGroupIcon, UserSettings01Icon, WorkflowSquare01Icon } from "@hugeicons/core-free-icons";
import { AppIcon, type HugeIcon } from "@/components/icons";
import { GhostButton, MiniMetric, PageHeader, SectionCard, StatusPill, Toolbar } from "@/components/ui";
import { formatCurrency } from "@/lib/utils";

type Config = {
  slug: string;
  eyebrow: string;
  title: string;
  description: string;
  action: string;
  icon: HugeIcon;
  metrics: { label: string; value: string; progress: number }[];
  rows: string[][];
};

const trend = [
  { month: "Jan", Complete: 72, Review: 18 },
  { month: "Feb", Complete: 78, Review: 15 },
  { month: "Mar", Complete: 83, Review: 12 },
  { month: "Apr", Complete: 80, Review: 16 },
  { month: "May", Complete: 88, Review: 9 },
  { month: "Jun", Complete: 92, Review: 7 },
];

const configs: Config[] = [
  { slug: "students", eyebrow: "Student registry", title: "Complete student profiles without ugly admin clutter.", description: "Identity, guardians, attendance, fees, grades, documents, notes, and activity stay in one clean operating profile.", action: "Add student", icon: StudentsIcon, metrics: [{ label: "Active students", value: "892", progress: 89 }, { label: "Guardian coverage", value: "98.7%", progress: 99 }, { label: "Watchlist", value: "28", progress: 18 }, { label: "Profiles complete", value: "91%", progress: 91 }], rows: [["Nadia Yusuf", "Grade 8A", "Maryam Noor", "97.8%", "Paid", "Active"], ["Brian Otieno", "Grade 7B", "Grace Wanjiku", "91.4%", "Partial", "Active"], ["Hana Abdi", "Grade 8A", "Abdi Yusuf", "78.2%", "Overdue", "Watchlist"]] },
  { slug: "teachers", eyebrow: "Staff operations", title: "Teacher workload, subjects, timetable, and access in one polished workspace.", description: "See each teacher’s department, assigned classes, weekly load, timetable state, and operating status.", action: "Add teacher", icon: TeacherIcon, metrics: [{ label: "Active teachers", value: "64", progress: 96 }, { label: "Avg workload", value: "27.6h", progress: 69 }, { label: "Covered periods", value: "98.1%", progress: 98 }, { label: "Conflicts", value: "0", progress: 100 }], rows: [["Amina Hassan", "Science", "8A, 9C", "28.5h", "Mapped", "Available"], ["David Mwangi", "Mathematics", "7A, 8B", "31h", "Mapped", "In class"], ["Leila Omar", "Languages", "7B, 9A", "25h", "Clean", "Planning"]] },
  { slug: "classes", eyebrow: "Academic structure", title: "Classes, sections, subjects, and teachers arranged like a real school model.", description: "Capacity, sections, class teachers, subjects, enrollment, attendance, and timetable health are grouped together.", action: "Create class", icon: School01Icon, metrics: [{ label: "Classes", value: "18", progress: 100 }, { label: "Sections", value: "54", progress: 92 }, { label: "Subjects", value: "32", progress: 88 }, { label: "Avg capacity", value: "91%", progress: 91 }], rows: [["Grade 7", "David Mwangi", "104 / 108", "8 subjects", "95.6%", "Active"], ["Grade 8", "Amina Hassan", "98 / 102", "9 subjects", "93.8%", "Active"], ["Grade 9", "Leila Omar", "92 / 96", "9 subjects", "94.2%", "Active"]] },
  { slug: "attendance", eyebrow: "Attendance operations", title: "Fast daily marking, clean review states, and automatic follow-up triggers.", description: "Daily sessions, class coverage, late arrivals, absences, locks, and parent alert prep stay organized.", action: "Mark attendance", icon: CalendarCheckIcon, metrics: [{ label: "Today present", value: "94.8%", progress: 95 }, { label: "Sessions complete", value: "48 / 52", progress: 92 }, { label: "Late arrivals", value: "24", progress: 31 }, { label: "Absences", value: "11", progress: 18 }], rows: [["Grade 7A", "34 / 36", "33", "1 late", "2 absent", "Complete"], ["Grade 7B", "32 / 34", "30", "2 late", "2 absent", "Review"], ["Grade 9C", "27 / 32", "26", "1 late", "5 absent", "Missing"]] },
  { slug: "fees", eyebrow: "Finance workspace", title: "Fee structures, invoices, payments, balances, reminders, and receipts in one clean flow.", description: "A proper operating ledger: calm tables, clear statuses, payment progress, and overdue controls.", action: "Create invoice", icon: Invoice03Icon, metrics: [{ label: "Collected", value: "KES 2.88M", progress: 76 }, { label: "Pending", value: "KES 238K", progress: 24 }, { label: "Overdue", value: "18", progress: 12 }, { label: "Accuracy", value: "99.4%", progress: 99 }], rows: [["INV-24001", "Nadia Yusuf", "Grade 8A", "KES 45,500", "KES 45,500", "Paid"], ["INV-24002", "Brian Otieno", "Grade 7B", "KES 42,000", "KES 20,000", "Partial"], ["INV-24003", "Hana Abdi", "Grade 8A", "KES 45,500", "KES 0", "Overdue"]] },
  { slug: "exams", eyebrow: "Exams and grades", title: "Assessments, grade entry, report readiness, rankings, and publishing built carefully.", description: "Academic teams can track term, class, subject, owner, completion, and report-card readiness clearly.", action: "Create assessment", icon: BookOpen01Icon, metrics: [{ label: "Assessments", value: "24", progress: 74 }, { label: "Grade completion", value: "83%", progress: 83 }, { label: "Reports ready", value: "78%", progress: 78 }, { label: "Approvals", value: "7", progress: 22 }], rows: [["Mathematics Midline", "Grade 8", "David Mwangi", "92%", "76.4%", "Grading"], ["Science Lab", "Grade 9", "Amina Hassan", "100%", "81.2%", "Ready"], ["English Composition", "Grade 7", "Leila Omar", "78%", "69.8%", "Open"]] },
  { slug: "timetable", eyebrow: "Timetable", title: "A visual timetable with class, teacher, room, and conflict awareness.", description: "Weekly planning, workload, room checks, and rule-based conflict detection without grid overload.", action: "Add slot", icon: Calendar02Icon, metrics: [{ label: "Published", value: "Term 2", progress: 100 }, { label: "Teacher conflicts", value: "0", progress: 100 }, { label: "Room conflicts", value: "0", progress: 100 }, { label: "Open slots", value: "6", progress: 18 }], rows: [["08:00", "Math 7A", "Science 8A", "English 9A", "Math 8B", "Ready"], ["09:00", "Science 7B", "Math 9A", "History 8A", "English 7A", "Ready"], ["10:30", "English 8A", "History 7A", "Math 7B", "Science 9C", "Clean"]] },
  { slug: "announcements", eyebrow: "Communication", title: "Announcements that feel controlled, targeted, and easy to audit.", description: "Publish to school, classes, teachers, parents, students, or staff with priority and read-status clarity.", action: "New announcement", icon: Megaphone01Icon, metrics: [{ label: "Published", value: "14", progress: 64 }, { label: "Read rate", value: "82%", progress: 82 }, { label: "Urgent", value: "2", progress: 12 }, { label: "Audiences", value: "8", progress: 90 }], rows: [["Assessment readiness", "Teachers", "High", "Today", "82% read", "Active"], ["Fee desk hours", "Parents", "Normal", "Yesterday", "64% read", "Active"], ["Attendance sweep", "Teachers", "Urgent", "Today", "91% read", "Active"]] },
  { slug: "automations", eyebrow: "Rules-based automations", title: "Useful school automations without fake AI or messy black boxes.", description: "Thresholds, triggers, and actions handle attendance risk, overdue invoices, timetable conflicts, and report readiness.", action: "Create rule", icon: WorkflowSquare01Icon, metrics: [{ label: "Active rules", value: "12", progress: 80 }, { label: "Runs", value: "188", progress: 88 }, { label: "Hours saved", value: "13h", progress: 72 }, { label: "Failed", value: "0", progress: 100 }], rows: [["Low attendance watchlist", "Attendance below 80%", "Active", "42 runs", "6h saved", "Active"], ["Invoice overdue guard", "Due date passed", "Active", "128 runs", "4h saved", "Active"], ["Timetable conflict monitor", "Slot changed", "Active", "18 runs", "3h saved", "Active"]] },
  { slug: "reports", eyebrow: "Reports and analytics", title: "Reports that are useful, scheduled, and clean enough for leadership meetings.", description: "Attendance integrity, fee collection, academic performance, risk, and operational quality stay clear.", action: "Generate report", icon: ChartLineData01Icon, metrics: [{ label: "Saved reports", value: "18", progress: 90 }, { label: "Scheduled", value: "7", progress: 70 }, { label: "Data health", value: "94%", progress: 94 }, { label: "Exports", value: "62", progress: 68 }], rows: [["Attendance Integrity", "Principal", "Every Friday", "92%", "Healthy", "Ready"], ["Fee Collection Pulse", "Accountant", "Every Monday", "86%", "Review", "Active"], ["Academic Board", "Academic Lead", "On demand", "78%", "Open", "Ready"]] },
  { slug: "settings", eyebrow: "System settings", title: "Settings organized by school operations, not random admin switches.", description: "School profile, academic setup, roles, permissions, automations, terms, branding, and integrations are grouped clearly.", action: "Update settings", icon: Settings02Icon, metrics: [{ label: "Setup health", value: "94%", progress: 94 }, { label: "Roles", value: "8", progress: 100 }, { label: "Terms", value: "3", progress: 100 }, { label: "Security", value: "Passed", progress: 100 }], rows: [["School profile", "Owner", "94%", "Low risk", "Complete", "Ready"], ["Academic setup", "Principal", "91%", "Low risk", "Ready", "Active"], ["Roles & access", "Admin", "100%", "Low risk", "Secure", "Active"]] },
];

const featureCards = [
  { icon: Target02Icon, title: "Operating signal", description: "Important school actions surface first.", status: "Active" },
  { icon: FilterHorizontalIcon, title: "Clean filters", description: "Search, date, class, owner, and status controls.", status: "Clean" },
  { icon: SecurityCheckIcon, title: "Role-ready", description: "Designed for owner, admin, teacher, accountant, parent, and student access.", status: "Secure" },
  { icon: Clock01Icon, title: "Automation-ready", description: "Rules can trigger tasks, alerts, and status updates.", status: "Ready" },
];

export default function ModuleRoute({ params }: { params: { module: string } }) {
  const config = configs.find((item) => item.slug === params.module);
  if (!config) notFound();
  const valueFormatter = config.slug === "fees" ? (value: number) => formatCurrency(value * 30000) : (value: number) => `${value}%`;

  return <div className="space-y-6"><PageHeader eyebrow={config.eyebrow} title={config.title} description={config.description} action={config.action} />
    <Grid numItems={1} numItemsMd={2} numItemsLg={4} className="gap-4">{config.metrics.map((metric) => <MiniMetric key={metric.label} {...metric} />)}</Grid>
    <Toolbar placeholder={`Search ${config.slug}, records, owners, classes, and statuses...`} right={<><GhostButton><span className="inline-flex items-center gap-2"><AppIcon icon={FilterHorizontalIcon} size={16} />Filters</span></GhostButton><GhostButton><span className="inline-flex items-center gap-2"><AppIcon icon={Download03Icon} size={16} />Export</span></GhostButton></>} />
    {config.slug === "attendance" || config.slug === "reports" ? <Card className="rounded-[1.5rem] border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_220px_220px]"><DateRangePicker /><Select defaultValue="all"><SelectItem value="all">All classes</SelectItem><SelectItem value="grade-7">Grade 7</SelectItem></Select><Select defaultValue="term"><SelectItem value="term">This term</SelectItem><SelectItem value="month">This month</SelectItem></Select></div></Card> : null}
    <div className="grid gap-4 xl:grid-cols-[1.08fr_0.92fr]"><SectionCard title={`${config.eyebrow} trend`} description="A clean operating trend showing completion and review pressure."><BarChart className="h-80" data={trend} index="month" categories={["Complete", "Review"]} colors={["slate", "blue"]} valueFormatter={valueFormatter} yAxisWidth={config.slug === "fees" ? 72 : 44} /></SectionCard><SectionCard title="Operating blueprint" description="Structured for real school work, with clarity before visual noise."><div className="grid gap-3 sm:grid-cols-2">{featureCards.map((feature) => <Card key={feature.title} className="rounded-2xl border-slate-200 bg-slate-50 p-4 shadow-none"><div className="flex items-start justify-between gap-3"><div className="rounded-xl bg-white p-2 text-slate-700 shadow-sm"><AppIcon icon={feature.icon} /></div><StatusPill status={feature.status} /></div><Title className="mt-4 text-sm font-semibold text-slate-950">{feature.title}</Title><Text className="mt-1 text-xs leading-5 text-slate-500">{feature.description}</Text></Card>)}</div></SectionCard></div>
    <SectionCard title={`${config.eyebrow} board`} description="A clean list view with useful context, status, and action-ready rows."><Table><TableHead><TableRow>{["Name", "Context", "Owner", "Metric", "Detail", "Status"].map((column) => <TableHeaderCell key={column}>{column}</TableHeaderCell>)}</TableRow></TableHead><TableBody>{config.rows.map((row, rowIndex) => <TableRow key={`${config.slug}-${rowIndex}`}>{row.map((cell, cellIndex) => <TableCell key={`${cell}-${cellIndex}`}>{cellIndex === 0 ? <span className="font-medium text-slate-950">{cell}</span> : cellIndex === row.length - 1 ? <StatusPill status={cell} /> : cell}</TableCell>)}</TableRow>)}</TableBody></Table></SectionCard>
  </div>;
}
