"use client";
import { AreaChart, BarChart, Card, DonutChart, FunnelChart, Grid, ProgressCircle, Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow, Text, Title, Tracker } from "@tremor/react";
import { AlertCircleIcon, CalendarCheckIcon, Invoice03Icon, School01Icon, StudentsIcon, WorkflowSquare01Icon } from "@hugeicons/core-free-icons";
import { AppIcon } from "@/components/icons";
import { KpiCard, MiniMetric, PageHeader, SectionCard, StatusPill } from "@/components/ui";
import { formatCurrency } from "@/lib/utils";

const attendanceTrend = [{ date: "Mon", Present: 94.2, Late: 3.4, Absent: 2.4 }, { date: "Tue", Present: 95.8, Late: 2.1, Absent: 2.1 }, { date: "Wed", Present: 93.7, Late: 3.9, Absent: 2.4 }, { date: "Thu", Present: 96.4, Late: 2.2, Absent: 1.4 }, { date: "Fri", Present: 94.9, Late: 2.9, Absent: 2.2 }];
const feeTrend = [{ month: "Jan", Collected: 2240000, Pending: 410000 }, { month: "Feb", Collected: 2360000, Pending: 360000 }, { month: "Mar", Collected: 2520000, Pending: 315000 }, { month: "Apr", Collected: 2410000, Pending: 455000 }, { month: "May", Collected: 2690000, Pending: 292000 }, { month: "Jun", Collected: 2880000, Pending: 238000 }];
const gradeDistribution = [{ grade: "A", Students: 86 }, { grade: "B", Students: 143 }, { grade: "C", Students: 118 }, { grade: "D", Students: 37 }, { grade: "E", Students: 8 }];
const pipelineData = [{ name: "Enrolled", value: 892 }, { name: "Active today", value: 851 }, { name: "Fully marked", value: 823 }, { name: "Needs follow up", value: 28 }];
const trackerData = [{ color: "emerald", tooltip: "Complete" }, { color: "emerald", tooltip: "Complete" }, { color: "yellow", tooltip: "Review" }, { color: "emerald", tooltip: "Complete" }, { color: "rose", tooltip: "Missing" }, { color: "emerald", tooltip: "Complete" }];
const stats = [
  { label: "Active students", value: "892", delta: "+4.8%", trend: "increase" as const, caption: "42 new admissions this term", icon: StudentsIcon },
  { label: "Attendance today", value: "94.8%", delta: "+1.2%", trend: "increase" as const, caption: "823 fully marked records", icon: CalendarCheckIcon },
  { label: "Fees collected", value: "KES 2.88M", delta: "+8.1%", trend: "increase" as const, caption: "76.4% of term target", icon: Invoice03Icon },
  { label: "Open alerts", value: "18", delta: "-6", trend: "decrease" as const, caption: "12 auto-resolved this week", icon: AlertCircleIcon },
];
const watchlist = [["Nadia Yusuf", "Grade 8A", "97.8%", "Paid", "Active"], ["Brian Otieno", "Grade 7B", "91.4%", "Partial", "Active"], ["Hana Abdi", "Grade 8A", "78.2%", "Overdue", "Watchlist"], ["Imani Noor", "Grade 9C", "88.6%", "Pending", "Active"]];
const events = [["Grade 9C attendance missing", "Critical", "Attendance sweep", "12 min ago"], ["3 invoices moved to overdue", "Warning", "Invoice guard", "1 hr ago"], ["No timetable conflicts detected", "Info", "Timetable monitor", "2 hrs ago"]];

export default function DashboardPage() {
  return <div className="space-y-6"><PageHeader eyebrow="Command center" title="Run the school day from one clean, reliable place." description="Edfica brings attendance, student care, finance, exams, communication, and operational automations into a calm premium workspace." action="Create record" />
    <Grid numItems={1} numItemsMd={2} numItemsLg={4} className="gap-4">{stats.map((stat) => <KpiCard key={stat.label} {...stat} />)}</Grid>
    <div className="grid gap-4 xl:grid-cols-[1.45fr_0.85fr]"><SectionCard title="Attendance health" description="Daily attendance is tracked by present, late, and absent states so leadership can see quality immediately." action="Open attendance"><AreaChart className="mt-2 h-80" data={attendanceTrend} index="date" categories={["Present", "Late", "Absent"]} colors={["emerald", "amber", "rose"]} valueFormatter={(value) => `${value}%`} showLegend showGridLines yAxisWidth={44} /><div className="mt-5 grid gap-3 md:grid-cols-3"><MiniMetric label="Sessions locked" value="48 / 52" progress={92} /><MiniMetric label="Late arrival rate" value="2.9%" progress={29} /><MiniMetric label="Unexplained absences" value="11" progress={18} /></div></SectionCard><SectionCard title="Today’s operating pipeline" description="A quick view from enrollment to follow-up."><FunnelChart className="h-72" data={pipelineData} color="slate" valueFormatter={(value) => value.toLocaleString()} showXAxis={false} showYAxis /><Tracker className="mt-5" data={trackerData} /><Text className="mt-3 text-xs text-slate-500">Green is complete, amber needs review, and red requires attention.</Text></SectionCard></div>
    <div className="grid gap-4 xl:grid-cols-3"><SectionCard title="Fee collection pulse" description="Term revenue, pending balances, and collection quality." className="xl:col-span-2"><BarChart className="h-80" data={feeTrend} index="month" categories={["Collected", "Pending"]} colors={["slate", "blue"]} valueFormatter={(value) => formatCurrency(value)} yAxisWidth={72} showLegend /></SectionCard><SectionCard title="Grade distribution" description="Academic performance across active assessments."><DonutChart className="h-60" data={gradeDistribution} index="grade" category="Students" colors={["emerald", "blue", "amber", "orange", "rose"]} valueFormatter={(value) => `${value} students`} /><div className="mt-5 grid grid-cols-2 gap-3"><MiniMetric label="Report readiness" value="78%" progress={78} /><MiniMetric label="Pending marks" value="46" progress={22} /></div></SectionCard></div>
    <div className="grid gap-4 xl:grid-cols-[1.15fr_0.85fr]"><SectionCard title="Students needing attention" description="Clean watchlist pulled from attendance, fees, and academic signals." action="View students"><Table><TableHead><TableRow>{["Student", "Class", "Attendance", "Fees", "Status"].map((heading) => <TableHeaderCell key={heading}>{heading}</TableHeaderCell>)}</TableRow></TableHead><TableBody>{watchlist.map((row) => <TableRow key={row[0]}>{row.map((cell, index) => <TableCell key={cell}>{index >= 3 ? <StatusPill status={cell} /> : cell}</TableCell>)}</TableRow>)}</TableBody></Table></SectionCard><SectionCard title="Automation feed" description="Rules-based school operations. No AI. Clear automated safeguards."><div className="space-y-3">{events.map(([title, severity, source, time]) => <Card key={title} className="rounded-2xl border-slate-200 bg-slate-50 p-4 shadow-none"><div className="flex items-start gap-3"><div className="rounded-xl bg-white p-2 text-slate-700 shadow-sm"><AppIcon icon={WorkflowSquare01Icon} size={18} /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><Title className="text-sm font-semibold text-slate-950">{title}</Title><StatusPill status={severity} /></div><Text className="mt-1 text-xs text-slate-500">{source} • {time}</Text></div></div></Card>)}</div><div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between gap-4"><div><Text className="text-xs text-slate-500">Operational quality</Text><Title className="mt-1 text-lg font-semibold text-slate-950">94%</Title></div><ProgressCircle value={94} radius={38} strokeWidth={8} color="emerald"><AppIcon icon={School01Icon} size={20} /></ProgressCircle></div></div></SectionCard></div>
  </div>;
}
