"use client";
import { AreaChart, BarChart, Card, Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow, Text } from "@tremor/react";
import { AlertCircleIcon, CalendarCheckIcon, ChartLineData01Icon, Invoice03Icon, StudentsIcon, TaskDone01Icon } from "@hugeicons/core-free-icons";
import { AppIcon } from "@/components/icons";
import { PageHeader, Panel, StatCard, StatusBadge } from "@/components/ui";

const attendance = [{ day: "Mon", Present: 94, Late: 3, Absent: 3 }, { day: "Tue", Present: 96, Late: 2, Absent: 2 }, { day: "Wed", Present: 93, Late: 4, Absent: 3 }, { day: "Thu", Present: 95, Late: 3, Absent: 2 }, { day: "Fri", Present: 94, Late: 3, Absent: 3 }];
const workload = [{ area: "Attendance", Complete: 92, Review: 8 }, { area: "Fees", Complete: 76, Review: 24 }, { area: "Grades", Complete: 81, Review: 19 }, { area: "Timetable", Complete: 97, Review: 3 }];
const tasks = [["Grade 8 attendance not locked", "Attendance", "Review"], ["Term 2 fee reminder batch", "Finance", "Pending"], ["Science assessment marks", "Exams", "Open"], ["Teacher workload check", "Timetable", "Ready"]];

export default function DashboardPage() {
  return <div className="space-y-6"><PageHeader label="Today" title="School operations overview" description="A quiet daily view for attendance, fees, academics, timetable status, and unresolved work. No decoration before function." action="Add task" /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><StatCard label="Attendance completion" value="92%" note="48 of 52 class sessions locked" icon={CalendarCheckIcon} progress={92} /><StatCard label="Open student flags" value="28" note="Attendance, finance, or grade review" icon={StudentsIcon} progress={18} /><StatCard label="Fee collection" value="76%" note="Uses configured school currency" icon={Invoice03Icon} progress={76} /><StatCard label="Report readiness" value="81%" note="Gradebooks and approvals" icon={ChartLineData01Icon} progress={81} /></div><div className="grid gap-4 xl:grid-cols-[1.4fr_0.9fr]"><Panel title="Attendance trend" description="Five-day attendance health by status."><AreaChart className="h-72" data={attendance} index="day" categories={["Present", "Late", "Absent"]} colors={["emerald", "amber", "rose"]} valueFormatter={(v) => `${v}%`} yAxisWidth={40} /></Panel><Panel title="Operations workload" description="Completion vs review pressure."><BarChart className="h-72" data={workload} index="area" categories={["Complete", "Review"]} colors={["blue", "slate"]} valueFormatter={(v) => `${v}%`} yAxisWidth={40} /></Panel></div><div className="grid gap-4 xl:grid-cols-[1fr_360px]"><Panel title="Priority work"><Table><TableHead><TableRow><TableHeaderCell>Item</TableHeaderCell><TableHeaderCell>Area</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell></TableRow></TableHead><TableBody>{tasks.map(([item, area, status]) => <TableRow key={item}><TableCell className="font-medium text-slate-950">{item}</TableCell><TableCell>{area}</TableCell><TableCell><StatusBadge>{status}</StatusBadge></TableCell></TableRow>)}</TableBody></Table></Panel><Panel title="Incident state" description="No active incident is better than another decorative card."><Card className="rounded-[6px] border border-emerald-200 bg-emerald-50 p-4 shadow-none"><div className="flex items-start gap-3"><AppIcon icon={AlertCircleIcon} size={20} className="mt-0.5 text-emerald-700" /><div><div className="text-sm font-semibold text-emerald-950">No critical incident</div><Text className="mt-1 text-sm text-emerald-800">Missing attendance and overdue invoices are being tracked as routine follow up.</Text></div></div></Card><div className="mt-3 flex items-center gap-2 rounded-[6px] border border-slate-200 bg-slate-50 p-3 text-sm text-slate-600"><AppIcon icon={TaskDone01Icon} size={16} /> 12 routine items completed this week.</div></Panel></div></div>;
}
