"use client";
import Link from "next/link";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow, Text } from "@tremor/react";
import { StudentsIcon, UserGroupIcon } from "@hugeicons/core-free-icons";
import { EmptyState, FilterBar, NativeButton, PageHeader, Panel, StatCard, StatusBadge } from "@/components/ui";

const rows = [["ADM-24001", "Nadia Yusuf", "Grade 8A", "Maryam Noor", "97.8%", "Complete"], ["ADM-24002", "Brian Otieno", "Grade 7B", "Grace Wanjiku", "91.4%", "Review"], ["ADM-24003", "Hana Abdi", "Grade 8A", "Abdi Yusuf", "78.2%", "Watchlist"]];

export default function StudentsPage() {
  return <div className="space-y-6"><PageHeader label="Registry" title="Students" description="Search, filter, inspect, and maintain student records without mixing finance, attendance, and academic details into one noisy table." action="Add student" /><div className="grid gap-4 md:grid-cols-3"><StatCard label="Active students" value="892" note="Across active academic year" icon={StudentsIcon} progress={89} /><StatCard label="Guardian coverage" value="98%" note="Primary contact assigned" icon={UserGroupIcon} progress={98} /><StatCard label="Profile completion" value="91%" note="Required fields finished" icon={StudentsIcon} progress={91} /></div><FilterBar placeholder="Search name, admission number, guardian, class"><NativeButton variant="soft">Class</NativeButton><NativeButton variant="soft">Status</NativeButton><NativeButton variant="soft">Export</NativeButton></FilterBar><div className="grid gap-4 xl:grid-cols-[1fr_360px]"><Panel title="Student registry"><Table><TableHead><TableRow><TableHeaderCell>Admission</TableHeaderCell><TableHeaderCell>Name</TableHeaderCell><TableHeaderCell>Class</TableHeaderCell><TableHeaderCell>Guardian</TableHeaderCell><TableHeaderCell>Attendance</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell></TableRow></TableHead><TableBody>{rows.map((row) => <TableRow key={row[0]}><TableCell>{row[0]}</TableCell><TableCell><Link href="/students/adm-24001" className="font-medium text-blue-700">{row[1]}</Link></TableCell><TableCell>{row[2]}</TableCell><TableCell>{row[3]}</TableCell><TableCell>{row[4]}</TableCell><TableCell><StatusBadge>{row[5]}</StatusBadge></TableCell></TableRow>)}</TableBody></Table></Panel><Panel title="Selected student" description="Keep the list clean. Show depth only when a student is selected."><div className="space-y-3"><div><Text className="text-xs text-slate-500">Student</Text><div className="text-sm font-semibold text-slate-950">Nadia Yusuf</div></div><div className="grid grid-cols-2 gap-2 text-sm"><div className="rounded-[6px] border border-slate-200 bg-slate-50 p-3"><div className="text-xs text-slate-500">Class</div><div className="font-medium text-slate-950">Grade 8A</div></div><div className="rounded-[6px] border border-slate-200 bg-slate-50 p-3"><div className="text-xs text-slate-500">Attendance</div><div className="font-medium text-slate-950">97.8%</div></div></div><EmptyState title="No unresolved note" description="Attendance, fee, discipline, and medical notes will appear here when action is needed." icon={StudentsIcon} /></div></Panel></div></div>;
}
