import { Card, Text, Title } from "@tremor/react";
import { Calendar02Icon, School01Icon, Settings02Icon, TeacherIcon } from "@hugeicons/core-free-icons";
import { AppIcon } from "@/components/icons";
import { NativeButton } from "@/components/ui";

const steps = [
  [School01Icon, "School profile", "Name, country, time zone, logo, and operating currency."],
  [Calendar02Icon, "Academic year", "Terms, grading scale, attendance threshold, and reporting periods."],
  [TeacherIcon, "People and roles", "Invite leadership, teachers, accountants, and front desk staff."],
  [Settings02Icon, "Rules", "Fee reminders, absence alerts, timetable conflict checks, and approvals."],
];

export default function OnboardingPage() {
  return <main className="min-h-screen bg-[#f7f8fa] px-4 py-8"><div className="mx-auto max-w-6xl"><div className="mb-6 border-b border-slate-200 pb-5"><div className="text-xs font-medium uppercase tracking-[0.14em] text-slate-500">Initial setup</div><h1 className="mt-2 text-2xl font-semibold tracking-[-0.03em] text-slate-950">Prepare Edfica before daily use.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">A school system needs clean setup before data entry. Configure the school, academic year, roles, and rules first.</p></div><div className="grid gap-5 lg:grid-cols-[0.78fr_1.22fr]"><div className="space-y-3">{steps.map(([icon, title, body], index) => <Card key={title as string} className="rounded-[6px] border border-slate-200 bg-white p-4 shadow-sm"><div className="flex gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-[6px] border border-blue-200 bg-blue-50 text-blue-700"><AppIcon icon={icon as any} size={18} /></div><div><div className="text-sm font-semibold text-slate-950">{index + 1}. {title as string}</div><p className="mt-1 text-sm leading-5 text-slate-500">{body as string}</p></div></div></Card>)}</div><Card className="rounded-[6px] border border-slate-200 bg-white p-6 shadow-sm"><Title className="text-base text-slate-950">School profile</Title><Text className="mt-1 text-sm text-slate-500">These values drive currency labels, timetable time zone, reports, and attendance rules.</Text><div className="mt-6 grid gap-4 md:grid-cols-2"><label className="block"><span className="text-sm font-medium text-slate-700">School name</span><input className="mt-1 h-10 w-full rounded-[6px] border border-slate-200 px-3 text-sm outline-none focus:border-blue-300 focus:ring-4 focus:ring-blue-50" placeholder="Edfica Academy" /></label><label className="block"><span className="text-sm font-medium text-slate-700">Country</span><input className="mt-1 h-10 w-full rounded-[6px] border border-slate-200 px-3 text-sm outline-none focus:border-blue-300 focus:ring-4 focus:ring-blue-50" placeholder="Select country" /></label><label className="block"><span className="text-sm font-medium text-slate-700">Time zone</span><input className="mt-1 h-10 w-full rounded-[6px] border border-slate-200 px-3 text-sm outline-none focus:border-blue-300 focus:ring-4 focus:ring-blue-50" placeholder="UTC" /></label><label className="block"><span className="text-sm font-medium text-slate-700">Default currency</span><input className="mt-1 h-10 w-full rounded-[6px] border border-slate-200 px-3 text-sm outline-none focus:border-blue-300 focus:ring-4 focus:ring-blue-50" placeholder="Configured per school" /></label></div><div className="mt-6 flex justify-end gap-2"><NativeButton variant="soft">Save draft</NativeButton><NativeButton>Continue</NativeButton></div></Card></div></div></main>;
}
